DROP TABLE votes IF EXISTS;
DROP TABLE menu IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE restaurant IF EXISTS;



DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;


CREATE TABLE restaurant
(
    id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE menu
(
    id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date  DATE NOT NULL ,
    price DOUBLE NOT NULL,
    description VARCHAR(255) NOT NULL,
    rest_id INTEGER NOT NULL,
    FOREIGN KEY (rest_id) REFERENCES restaurant (id)
  -- //ON DELETE CASCADE
);
CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  isAdmin          BOOLEAN     NOT NULL

);


CREATE TABLE votes
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id          INTEGER NOT NULL,
  rest_id          INTEGER NOT NULL,
  date             DATE     NOT NULL ,
  FOREIGN KEY (rest_id) REFERENCES restaurant (id) ,
  FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE UNIQUE INDEX votes_unique_user_date_idx ON votes (user_id, date);

