/*DROP TABLE users IF EXISTS;
DROP TABLE lunch IF EXISTS;*/
DROP TABLE menu IF EXISTS;
DROP TABLE restaurant IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE votes IF EXISTS;

DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;


CREATE TABLE restaurant
(
    id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE menu
(
    id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date  DATE NOT NULL ,
    price DOUBLE NOT NULL,
    description VARCHAR(255) NOT NULL,
    rest_id INTEGER NOT NULL,
    FOREIGN KEY (rest_id) REFERENCES RESTAURANT (id) ON DELETE CASCADE
);
CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  isAdmin          BOOLEAN     NOT NULL

);
/*CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE votes
(
  user_id INTEGER NOT NULL,
  rest_id INTEGER NOT NULL,
  date DATE NOT NULL ,
  FOREIGN KEY (rest_id) REFERENCES RESTAURANT (id) ,
  FOREIGN KEY (user_id) REFERENCES RESTAURANT (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX votes_unique_user_date_idx ON votes (user_id, date)*/
/*

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE meals
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  date_time   TIMESTAMP    NOT NULL,
  description VARCHAR(255) NOT NULL,
  calories    INT          NOT NULL,
  user_id     INTEGER      NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX meals_unique_user_datetime_idx ON meals (user_id, date_time)*/
